# Generated by Django 5.2.4 on 2025-07-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lineup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "map",
                    models.CharField(choices=[("Mirage", "Mirage")], max_length=255),
                ),
                (
                    "grenade_type",
                    models.CharField(
                        choices=[
                            ("Explosive", "Explosive"),
                            ("Smoke", "Smoke"),
                            ("Flash", "Flash"),
                        ]
                    ),
                ),
                ("author", models.CharField(max_length=255)),
                ("video", models.FileField(upload_to="videos/")),
            ],
        ),
    ]
