# Generated by Django 5.2.4 on 2025-07-28 19:42

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineup",
            name="pub_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lineup",
            name="author",
            field=models.CharField(default="Unknown", max_length=35),
        ),
        migrations.AlterField(
            model_name="lineup",
            name="grenade_type",
            field=models.CharField(
                choices=[
                    ("explosive", "Explosive"),
                    ("smoke", "Smoke"),
                    ("flash", "Flash"),
                ],
                default="smoke",
            ),
        ),
        migrations.AlterField(
            model_name="lineup",
            name="map",
            field=models.CharField(choices=[("mirage", "Mirage")], default="mirage"),
        ),
        migrations.AlterField(
            model_name="lineup",
            name="title",
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name="lineup",
            name="video",
            field=models.FileField(
                upload_to="videos",
                validators=[django.core.validators.FileExtensionValidator(["mp4"])],
            ),
        ),
    ]
