version: '3.13'

services:
  db:
    image: ${POSTGRES_IMAGE}
    container_name: db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    env_file:
      - ../.env
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $${DB_USER} -d $${DB_NAME}'" ]
      interval: 3s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ..
      dockerfile: /src/api/Dockerfile
    image: cs2smokes_backend:latest
    container_name: backend
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
#      - ../.data/logs/:/.data/logs/
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --clear --noinput &&
               uvicorn api.asgi:application --host 0.0.0.0 --port 8000"
    expose:
      - "8000"
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy

  bot:
    build:
      context: ..
      dockerfile: /src/bot/Dockerfile
    image: cs2smokes_bot:latest
    container_name: bot
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
      - ../.data/bot_logs/:/.data/logs/
    command: >
      bash -c "python aiogram_run.py"
    expose:
      - "8000"
    env_file:
      - ../.env

  nginx:
    image: ${NGINX_IMAGE}
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
    env_file:
      - ../.env
      - .env

volumes:
  db_data:
  static:
  media:
